### ISSUE TITLE
Error: Cannot find module 'node-mfcc'

### ISSUE THREAD

**Issue by drumnicorn** [joshjung/node-mfcc#10]
ERROR:
```
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'node-mfcc'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\robin\OneDrive\Dokumente\GitHub\SongClassification-CHEROB-PC\test.js:1:70)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```
code (test.js)
`MFCC = require("node-mfcc");`

Node: v10.13.0
NPM: 6.11.2
OS: Windows 10 64bit

**Comment by joshjung** [comment]
Did you use npm to install it?
